matrix:
- name: Blog Content
  aspell:
    lang: en
  dictionary:
    encoding: utf-8
    wordlists:
      - .wordlist.txt
  pipeline:
  # ignore the docasaurus "title" custom code fence attribute
  - pyspelling.filters.context:
      context_visible_first: true
      delimiters:
        - open: '(?<=^```)(.*) title=.*'
          close: '$'
  - pyspelling.filters.markdown:
      markdown_extensions:
        - markdown.extensions.fenced_code
  - pyspelling.filters.html:
      comments: false
      ignores:
      - pre
      - code
  sources:
  - 'docs/**/*'
  - 'src/components/**'
  - 'src/pages/**'
  default_encoding: utf-8
